server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://***.***.**.**:3306/authDB?createDatabaseIfNotExist=true
    username: user
    password: pass
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace